trigger: none

pool:
  vmimage: 'windows-latest'

stages:
 - stage: Build
   jobs:
    - job: Build_Reports
      steps:
        - checkout: self
          path: 'self'
        - task: PowerShell@2
          displayName: 'Download PBIXInspector'
          inputs:
            targetType: inline
            script: |
              $path = "$(Build.SourcesDirectory)"
              $toolsPath = "$path\_Tools"
              $downloadUrl = "https://github.com/NatVanG/PBI-Inspector/releases/download/v1.8.1-CLI/win-x64-v1.8.1-CLI.zip" 
              $zipFile = "$path\PBIXInspector.zip"
              Invoke-WebRequest -Uri $downloadUrl -OutFile $zipFile
              Expand-Archive -Path $zipFile -DestinationPath $toolsPath -Force
              Remove-Item $zipFile
              Remove-Item $path\_Tools\win-x64\CLI\Files -Force -Recurse
              Write-Host "Tools path: $toolsPath"
        - task: PowerShell@2
          displayName: 'Run Report Rules'
          inputs:
            targetType: inline
            script: |
                  $path = Resolve-Path "."
                  $toolPath =  "$path\_Tools\win-x64\CLI\PBIXInspectorCLI.exe"
                  $rulesPath = "$path\Rules-Report.json"

                  $itemsFolders = Get-ChildItem  -Path $path -recurse -include *.pbir

                  foreach($itemFolder in $itemsFolders)
                  {	
                      $itemPath = $itemFolder.Directory.FullName
                      
                      Write-Host "Processing '$itemPath'"

                      Start-Process -FilePath "$toolPath" -ArgumentList "-pbipreport ""$itemPath"" -rules ""$rulesPath"" -formats ""ADO""" -NoNewWindow -Wait
                  }

    - job: Build_Datasets
      steps:
        - checkout: self
          path: 'self'
        - task: PowerShell@2
          displayName: 'Download TE'
          inputs:
            targetType: inline
            script: |
              $path = "$(Build.SourcesDirectory)"
              $toolsPath = "$path\_Tools"
              $TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.18.2/TabularEditor.Portable.zip" 
              $zipFile = "$path\TabularEditor.zip"
              Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $zipFile
              Expand-Archive -Path $zipFile -DestinationPath $toolsPath -Force
              Remove-Item $zipFile
              Write-Host "Tools path: $toolsPath"          
        - task: PowerShell@2
          displayName: 'Run Dataset Rules'
          inputs:
            targetType: inline
            script: |
              $path = "$(Build.SourcesDirectory)"
              $toolPath = "$path\_Tools\TabularEditor.exe"
              $rulesPath = "$path\Rules-Dataset.json"

              $itemsFolders = Get-ChildItem  -Path $path -recurse -include *.pbidataset

              foreach($itemFolder in $itemsFolders)
              {	
                  $itemPath = "$($itemFolder.Directory.FullName)\Model.bim"

                  Write-Host "Processing '$itemPath'"

                  Start-Process -FilePath "$toolPath" -ArgumentList """$itemPath"" -A ""$rulesPath"" -V" -NoNewWindow -Wait
              }

    
