variables:
  - name: 'pipelineName'
    value: 'RR - Sales Analytics (AnalytiCats)'

trigger:
  branches:
    include:
    - main   
  paths:
    include:
    - '*.Dataset/*'
    - '*.Report/*'
    # exclude:
    # - '*.yml'

pool:
  vmimage: 'windows-latest'

stages:
 - stage: Test  
   jobs:
      - deployment: Deploy
        displayName: "Deploy to Test"
        environment: "Test"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ms-pbi-api.pbi-automation-tools.Pipelines_Deploy.DeploymentPipelines-Deploy@1
                  displayName: 'Run Deployment Pipeline'
                  inputs:
                    pbiConnection: SP_RR_DevMode_Deploy
                    pipeline: $(pipelineName)
                    stageOrder: Test
                    note: "$(Build.SourceVersion)"
                    deployType: All
                    createNewWS: false
                - task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
                  displayName: 'Refresh Dataset'
                  inputs:
                    PowerBIServiceEndpoint: 'PowerBIActions_SP'
                    Action: DataRefresh
                    WorkspaceName: 'RR - Sales Analytics {TEST}'
                    DatasetName: Sales

 - stage: Production  
   jobs:
      - deployment: Deploy
        displayName: "Deploy to Production"
        environment: "Production"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ms-pbi-api.pbi-automation-tools.Pipelines_Deploy.DeploymentPipelines-Deploy@1
                  displayName: 'Run Deployment Pipeline'
                  inputs:
                    pbiConnection: SP_RR_DevMode_Deploy
                    pipeline: $(pipelineName)
                    stageOrder: Production
                    note: "$(Build.SourceVersion)"
                    deployType: All
                    createNewWS: false
                    updateApp: true
                - task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
                  displayName: 'Refresh Dataset'
                  inputs:
                    PowerBIServiceEndpoint: 'PowerBIActions_SP'
                    Action: DataRefresh
                    WorkspaceName: 'RR - Sales Analytics {PRD}'
                    DatasetName: Sales
